//
//  CodingKeys.swift
//  OrdermentumSDK
//
//  Created by Brandon Stillitano on 12/3/19.
//  Copyright © 2019 Ordermentum Pty Ltd. All rights reserved.
//

import Foundation

enum CodingKeys: String, CodingKey {
    // Main
    case meta
    case links
    case data

    // Meta
    case totalResults
    case totalPages
    case pageSize
    case pageNo

    //Links
    case linksSelf = "self"
    case first
    case next
    case prev
    case last

    //Image
    case secure_url
    case original
    case logo
    case icon
    case print
    case mini
    case small
    case medium
    case large

    //Flags
    case addons = "add-ons"
    case addVenue = "add-venue"
    case couponCodes = "coupon-codes"
    case dashboardProfile = "dashboard_profile"
    case findSupplier = "find-supplier"
    case googleSignIn = "google-sign-in"
    case homePopularProducts = "home-popular-products"
    case notificationCentre = "notification-centre"
    case paymentUpsellDialogCheckout = "payment-upsell-dialog-checkout"
    case paymentUpsellDialogCheckoutGiftCard = "payment-upsell-dialog-checkout-giftcard"
    case paymentUpsellDialogInvoice = "payment-upsell-dialog-invoice"
    case pendingSuppliers = "pending-suppliers"
    case popularProducts = "popular-products"
    case projectionsV2 = "projections-v2"
    case recommendedSuppliers = "recommended-suppliers"
    case retailerHome = "retailer-home"
    case retailerSignup = "retailer-signup"
    case retailerSignupCardModal = "retailer-signup-card-modal"
    case review
    case userInvite = "user-invite"
    case retailerHomeSupplierSearch = "retailer-home-supplier-search"

    //Generic
    case abn
    case accessNewRetailerUi
    case account
    case accountId
    case accounting
    case accountName
    case accountSettings
    case actionedBy
    case actionedById
    case actionedByName
    case actionLabel
    case active
    case activeRetailerIds
    case activity
    case activityEnded
    case address
    case addressableId
    case addressableType
    case addressId
    case address_id
    case addTax
    case admin
    case adminPerms
    case agreementRequired
    case alerts
    case alias
    case approvedByName
    case archived
    case attacheXml
    case autoConnect
    case availableDeliveries
    case backgroundColor
    case bankConfigured
    case banking
    case basePrice
    case batchCode
    case billingAddress
    case billingAddressId
    case billingAddressLine
    case billingEnd
    case billingEndDate
    case billingStart
    case billingStartDate
    case body
    case brand
    case brandImages
    case bsb
    case byhour
    case byminute
    case byRetailer
    case bySupplier
    case cancelled
    case cancelledAt
    case cancelledByName
    case canCharge
    case canMarkAsPaid
    case canMarkAsUnpaid
    case canRequestPaymentMethod
    case cardConfigured
    case cardDisplay
    case cardLast4Digits
    case cardName
    case cardOrDirect
    case cardType
    case cart
    case cartErrorCount
    case cartInfoCount
    case cartWarningCount
    case categories
    case category
    case chargable
    case chargeAt
    case chargedAt
    case chargedBy
    case chargedByUser
    case chargedByUserId
    case charged_by_user_id
    case classicStandingOrders
    case closeHour
    case closeMinute
    case code
    case color
    case comment
    case comments
    case complete
    case completeAt
    case completedAt
    case connect
    case connectionEmail
    case connectUrl
    case contactEmail
    case contactFirstName
    case contactLastName
    case content
    case corporateEntity
    case cost
    case country
    case createdAt
    case createdBy
    case createdByName
    case created_at
    case creation
    case credit
    case creditCard
    case creditNoteIds
    case customers
    case cutoff
    case cutOffPassed
    case cutOffTime
    case daily
    case darkBackgroundColor
    case darkTextColor
    case dataAttributes
    case date
    case dateLabel
    case days
    case dayStart
    case deactivatedAt
    case deeplink
    case defaultDeliveryDelay
    case defaultNotifications
    case defaultPaymentMethodType
    case defaultSalesAccountCode
    case defaultSchedule
    case deletedAt
    case deletedById
    case deleted_by_id
    case deleted_at
    case deliveries
    case delivery
    case deliveryAt
    case deliveryDate
    case deliveryDays
    case deliveryDelay
    case deliveryInstructions
    case demoSupplier
    case description
    case device
    case directDebit
    case directProcessing
    case disabled
    case disconnectUrl
    case discounts
    case discountSavings
    case display
    case displayName
    case displayUOM
    case dob
    case dueAt
    case dueDate
    case editable
    case editableUntil
    case effects
    case email
    case emailedTo
    case enabled
    case enableDeliveryDate
    case enableEmail
    case enableSMS
    case endDate
    case endOfMonth
    case endOfWeek
    case entityName
    case entityNotifications
    case entityType
    case errors
    case escalationTime
    case eventId
    case expenseAccountCode
    case experimentId
    case externalCustomerId
    case externalId
    case fileType
    case financeAvailable
    case firstName
    case firstReminder
    case flags
    case format
    case formatted
    case formattedPrice
    case fortnightly
    case freight
    case freightGroup
    case freightGroupId
    case freq
    case frequency
    case fri
    case fromRetailers
    case fullName
    case globalBakeXml
    case group
    case groupPayments
    case growthEngine
    case growthEnginePlus
    case gst
    case hasAgreed
    case hasAvailableDeliveries
    case hasRequestedPaymentMethod
    case hasScheduledOrder
    case hasTerms
    case height
    case hostId
    case id
    case images
    case imageURL
    case includeOrderUpdatesInReports
    case includeWeekends
    case industryType
    case infos
    case insights
    case integrationData
    case interval
    case invoice
    case invoiceEmailDelay
    case invoiceFrequency
    case invoiceId
    case invoiceIds
    case invoiceNumber
    case invoicePrefix
    case invoiceReference
    case invoiceSendAt
    case invoiceSentAt
    case invoiceSetting
    case invoiceStatus
    case invoiceSyncedAt
    case isAdmin
    case isApproved
    case isCancellable
    case isCancelled
    case isCard
    case isDirect
    case isEditable
    case isLocked
    case isOpen
    case isOutstanding
    case isReceivable
    case isReinstatable
    case isRetailerEditable
    case issue
    case isSuperAdmin
    case isUpdated
    case label
    case lastAgreed
    case lastFinishedAt
    case lastInvoiceSyncedAt
    case lastName
    case lastStartedAt
    case latitude
    case leadTime
    case legalName
    case lineItemComments
    case lineItemErrorCount
    case lineItemInfosCount
    case lineItems
    case lineItemWarningCount
    case link
    case liquorLicense
    case liquorLicenseRequired
    case live
    case locked
    case longitude
    case looseCount
    case marketplace
    case marketplaceLabel
    case marketplacePurchaser
    case marketplaceSupplier
    case maskedNumber
    case mergeable
    case mergeEventId
    case message
    case minimumOrderValue
    case minQuantity
    case mon
    case monthly
    case monthStart
    case mostOrdered
    case name
    case nextFinishAt
    case nextRun
    case nextRunAt
    case nextRunCancelled
    case nextRunDate
    case noPaymentActions
    case notes
    case notifications
    case number
    case onPlace
    case openHour
    case openMinute
    case orderedAt
    case orderExports
    case orderId
    case ordermentum
    case orderNumber
    case orderPrefix
    case orders
    case orderSchedule
    case ordersCsv
    case ordersDeliveryManifestPdf
    case ordersDeliveryPdf
    case ordersDeliverySummaryPdf
    case ordersInvoicePdf
    case ordersLineItemsCsv
    case ordersLineItemsDetailsCsv
    case ordersPickPdf
    case ordersProductionCsv
    case ordersProductionReportPdf
    case orderStatus
    case orderType
    case origin
    case other
    case outOfStock
    case overdueOrders
    case packCount
    case paidAt
    case paidSupplierAt
    case paidToSupplier
    case parentNotifications
    case passwordResetSentAt
    case passwordResetToken
    case payable
    case paymentDelay
    case paymentMethod
    case paymentMethodId
    case paymentMethodType
    case paymentMethodTypes
    case paymentOptions
    case paymentRecurrence
    case paymentSchedule
    case paymentSentAt
    case paymentSentBy
    case paymentStatus
    case paymentTerms
    case paymentTransactionId
    case payOnPlace
    case permalink
    case permissions
    case phone
    case place
    case placedAt
    case placedById
    case placedByName
    case placedOrders
    case plan
    case poa
    case pos
    case positions
    case postcode
    case price
    case priceFromTotal
    case priceGroup
    case priceGroupId
    case priceInc
    case primaryCategory
    case primaryProducts
    case processing
    case processingError
    case product
    case productCategories
    case productCount
    case productExports
    case productId
    case product_id
    case productsCsv
    case profileImage
    case profilePercent
    case projections
    case promotedCategories
    case promotional
    case properties
    case publicDirectory
    case public_id
    case purchaser
    case purchaserId
    case purchaserName
    case purchaserScheduleId
    case purchaser_id
    case pushNotifications
    case quantity
    case quantityThreshold
    case queued
    case randomWeight
    case ratePrice
    case read
    case readUrl
    case recipientEmail
    case recipientEntityName
    case recipientFirstName
    case recipientFullName
    case recipientLastName
    case recipientPhone
    case reckonReport
    case recurrence
    case recurrenceInfo
    case reference
    case referenceId
    case remindedAt
    case remittance
    case reportedBy
    case resolution
    case resolvedAt
    case resource_type
    case restart
    case retailer
    case retailerAddress
    case retailerAddressLine
    case retailerAlias
    case retailerChargeable
    case retailerDataAttributes
    case retailerEditable
    case retailerEmail
    case retailerExports
    case retailerId
    case retailerLegalName
    case retailerName
    case retailerPhone
    case retailerRecipient
    case retailers
    case retailerSender
    case retailerTradingName
    case retailer_id
    case role
    case roles
    case runAt
    case runStatus
    case salePercentage
    case salesCode
    case sameDeliveryAndBillingAddress
    case sat
    case schedule
    case scheduled
    case scheduleEnabled
    case scheduleId
    case scheduleName
    case schedules
    case seenAt
    case senderEntityName
    case senderId
    case senderType
    case sendInvoice
    case sentLateNotificationAt
    case sentOverdueNotificationAt
    case sequence
    case serviceAreas
    case settings
    case settlementReference
    case setupComplete
    case sharedSecret
    case shortName
    case show
    case showDirectoryPrice
    case signature
    case single
    case SKU
    case slot
    case slotName = "slotName"
    case slug
    case sortOrder
    case sponsored
    case standingOrders
    case startDate
    case state
    case status
    case statusLabel
    case stopCredit
    case street1
    case street2
    case submittedAt
    case subtext
    case subtotal
    case suburb
    case success
    case sun
    case superAdmin
    case supplier
    case supplierId
    case supplierName
    case supplierQuote
    case supplierRecipient
    case suppliers
    case supplierSender
    case supplier_id
    case surcharge
    case survey_scheduled_at
    case syncError
    case target
    case tax
    case taxable
    case taxType
    case textColor
    case thu
    case timeZone
    case timezone
    case title
    case token
    case toRetailer
    case total
    case totalCost
    case totalDiscount
    case totalDue
    case totalFreight
    case totalFreightIncGST
    case totalFreightTax
    case totalGST
    case totalPaid
    case totalQuantity
    case totalSavings
    case totalSponsoredDiscount
    case totalSupplierDiscount
    case totalWeight
    case tradingHours
    case tradingName
    case trending
    case tue
    case type
    case unit
    case unitPrice
    case unitSize
    case uom
    case updatedAt
    case updatedBy
    case updatedById
    case updatedByName
    case updatedUserId
    case updated_at
    case updated_by_id
    case updateUrl
    case uploadUrls
    case url
    case user
    case userId
    case user_id
    case value
    case valueThreshold
    case variantId
    case venue
    case venueTypes
    case verifiedAt
    case version
    case videoUrl
    case visibilityGroup
    case visibilityGroupId
    case visible
    case warnings
    case wed
    case weekly
    case weight
    case weightType
    case width
}
