//
//  ContentType.swift
//  
//
//  Created by Brandon Stillitano on 3/6/21.
//

import Foundation

public enum ContentType: String {
    case aac = "audio/aac"
    case abw = "application/x-abiword"
    case arc = "application/x-freearc"
    case avi = "video/x-msvideo"
    case azw = "application/vnd.amazon.ebook"
    case bin = "application/octet-stream"
    case bmp = "image/bmp"
    case bz = "application/x-bzip"
    case b2z = "application/x-bzip2"
    case cda = "application/x-cdf"
    case csh = "application/x-csh"
    case css = "text/css"
    case csv = "text/csv"
    case doc = "application/msword"
    case docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    case eot = "application/vnd.ms-fontobject"
    case epub = "application/epub+zip"
    case gz = "application/gzip"
    case gif = "image/gif"
    case html = "text/html"
    case ico = "image/vnd.microsoft.icon"
    case ics = "text/calendar"
    case jar = "application/java-archive"
    case jpeg = "image/jpeg"
    case js = "text/javascript"
    case json = "application/json"
    case jsonLd = "application/ld+json"
    case midi = "audio/midi"
    case midiX = "audio/x-midi"
    case mp3 = "audio/mpeg"
    case mp4 = "video/mp4"
    case mpeg = "video/mpeg"
    case mpkg = "application/vnd.apple.installer+xml"
    case odp = "application/vnd.oasis.opendocument.presentation"
    case ods = "application/vnd.oasis.opendocument.spreadsheet"
    case odt = "application/vnd.oasis.opendocument.text"
    case oga = "audio/ogg"
    case ogv = "video/ogg"
    case ogx = "application/ogg"
    case opus = "audio/opus"
    case otf = "font/otf"
    case pdf = "application/pdf"
    case php = "application/x-httpd-php"
    case png = "image/png"
    case ppt = "application/vnd.ms-powerpoint"
    case pptx = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    case rar = "application/vnd.rar"
    case rtf = "application/rtf"
    case sh = "application/x-sh"
    case svg = "image/svg+xml"
    case swf = "application/x-shockwave-flash"
    case tar = "application/x-tar"
    case tiff = "image/tiff"
    case ts = "video/mp2t"
    case ttf = "font/ttf"
    case txt = "text/plain"
    case vsd = "application/vnd.visio"
    case wav = "audio/wav"
    case weba = "audio/webm"
    case webm = "video/webm"
    case webp = "image/webp"
    case woff = "font/woff"
    case woff2 = "font/woff2"
    case xhtml = "application/xhtml+xml"
    case xls = "application/vnd.ms-excel"
    case xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    case xml = "application/xml"
    case xul = "application/vnd.mozilla.xul+xml"
    case zip = "application/zip"
    case z7 = "application/x-7z-compressed"
}
