# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.67.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = '1'
    cocoapods
    # carthage
  end

  desc "Runs all the unit tests"
  lane :test do
    # scan(scheme: "ordermentum-swift-sdk", devices: ["iPhone X", "iPad Air"])
    scan(workspace: "OrdermentumSDK.xcworkspace", devices: ["iPhone X"])
  end

  lane :lint do
    swiftlint(
      mode: :lint,
      strict: true)
  end

  lane :symbols do 
    sentry_upload_dsym(
      auth_token: '225882c846d143539935599eb4998ab6b16d074da6c04bff963aba2f1bc1bba1',
      org_slug: 'ordermentum',
      project_slug: 'ios'
   )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
